import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import BottomNavigation from "@/component/common/bottom-navigation";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main className="pt-5 px-5 pb-20 mb-5">{children}</main>;
}
